### PR TITLE
Supports Vim's gdefault option.

### PR DESCRIPTION
**Pull request by mkiken**
Changes Proposed in this Pull Request:

- Add gdefault, nogdefault command
- Add Gdefault GUI setting

I have written tests for:

- New features introduced

### CODE REVIEW

**Comment by mkiken** [comment]
Why test fail...?

**Comment by hultberg** [comment]
@mkiken See #188, they fail because of an bug in atom.

**Comment by mkiken** [comment]
@hultberg [The test result on my branch](https://travis-ci.org/lloeki/ex-mode/jobs/264011313) seems different from result on #188.
What's wrong...?

**Comment by hultberg** [comment]
@mkiken Indeed, looks like something new in atom as a new stable and beta has been released, just take a look at the current stable tests.

**Comment by hultberg** [comment]
Thanks for this @mkiken 🎉

**Pull request merged**
