### PR TITLE
adding support for splitright and splitbelow

### PR DESCRIPTION
**Pull request by dragonxlwang**
Hi @LongLiveCHIEF, as discussed in #132, here's a simple solution that add versatility of splitting

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
We need to add tests to `/spec/ex-commands-spec.coffee` for this.  I'd also like to add in support for `:set splitbelow` and `:set splitright`.

**Comment by dragonxlwang** [comment]
Please go ahead to the test :P 

I personally don't favor using "set" command but instead adding option to package settings. It's also easy to expose the splitbelow and splitright as ex commands

**Comment by LongLiveCHIEF** [comment]
@dragonxlwang any luck finishing the tests for your PR yet?

**Comment by dragonxlwang** [comment]
didn't realize that you asked me to add the test...

Treid to add test in #141, and hope this works.

**Comment by LongLiveCHIEF** [comment]
We don't need 2 PR's for this, just push your tests to your master so they are included in *this* PR. Thanks!

**Comment by dragonxlwang** [comment]
updated

**Comment by LongLiveCHIEF** [comment]
Thanks! Looks good. I'll double-check everything tomorrow to make sure it works with other updates going into the `0.9.0` release.

**Pull request merged**
