### PR TITLE
Issue #29 Command and file autocomplete

### LINKED ISSUE #29: Implement tab completion
Implementing tab completion for both commands and file paths would be a great feature to add.

### PR DESCRIPTION
**Pull request by stuartquin**
Fixes #29  .

**Note** I have not tested this on windows, assistance here would be much appreciated

Changes Proposed in this Pull Request:
- Adds a listener for the tab key to trigger autocomplete
- Autocompletes commands if only 1 word entered, otherwise paths

I have written tests for:

- [x] New features introduced
- [ ] Bugs fixed
- [ ] Neither (I'm just enhancing tests!)

@jazzpi @LongLiveCHIEF

### CODE REVIEW

**Comment by jazzpi** [comment]
This looks great on a first look, but could you explain how the command completion works? It currently can't autocomplete `:wr` and `:w` gets completed to `:wqa`.

**Comment by stuartquin** [comment]
Hi @jazzpi 

I grab the list of commands registered on the `Ex` singleton - https://github.com/lloeki/ex-mode/pull/155/files#diff-5745495f49c3f9334eec026f9b9418afR112

I've just pushed a commit to sort these alphabetically.

I'm not familiar with `:wr`, is there a better place to get a list of registered commands?

**Comment by jazzpi** [comment]
`:wr` would just be a shorthand to `:write` which is the full command for `:w`. Currently command matching is done in `lib/command.coffee`, but that also just sorts the commands alphabetically (which is technically incorrect actually) so it's probably the best if the autocomplete is consistent with that :smile:

**Comment by stuartquin** [comment]
Hi @jazzpi 

I've updated the `Ex.getCommands` method to return a list off all keys registered with both the instance and the prototype.
It then filters them to get uniques.

This seems to get everything and works with extensions using `registerCommand`

**Comment by jazzpi** [comment]
Great, thank you so much! This is amazing!

**Pull request merged**
