### PR TITLE
Stop using non-standard Promise.defer()

### LINKED ISSUE #147: error with `:w`.  Uncaught TypeError: Promise.defer is not a function
Uncaught TypeError: Promise.defer is not a function

```
TypeError: Promise.defer is not a function
    at Ex.write (/home/kminehart/.atom/packages/ex-mode/lib/ex.coffee:197:24)
    at Ex.w (/home/kminehart/.atom/packages/ex-mode/lib/ex.coffee:228:6)
    at /home/kminehart/.atom/packages/ex-mode/lib/ex.coffee:1:1
    at Command.execute (/home/kminehart/.atom/packages/ex-mode/lib/command.coffee:153:7)
    at ExState.processOpStack (/home/kminehart/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
    at ExState.pushOperations (/home/kminehart/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
    at ExViewModel.ViewModel.confirm (/home/kminehart/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
    at ExViewModel.module.exports.ExViewModel.confirm (/home/kminehart/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
    at ExViewModel.confirm (/home/kminehart/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
    at ex-command-mode-input.ExCommandModeInputElement.confirm (/home/kminehart/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:51:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-git/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom-git/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-git/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-git/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-git/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom-git/resources/app.asar/src/window-event-handler.js:3:61)
````

### Atom Version
```
⋊> ~/W/W/c/cocagne on 257167761 ⨯ atom-git --version
Atom    : 1.10.0-dev-21d3b67
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

### Ex-mode version
0.8.0

is using `atom-git` biting me here?

### PR DESCRIPTION
**Pull request by AsaAyers**
Fixes #147

Changes Proposed in this Pull Request:
- Replaced `Promise.defer()` with a custom `defer()` implementation

@jazzpi @LongLiveCHIEF

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
I believe the only thing holding this patch up, is someone seriously committed to maintaining and advancing it. see: [#116 - Looking for a New Maintainer](https://github.com/lloeki/ex-mode/issues/116)

I'd be willing to merge and publish if [*this one last time*](https://github.com/lloeki/ex-mode/issues/147#issuecomment-236959518) if @lloeki were to restore my permissions ([which I requested be removed](https://github.com/lloeki/ex-mode/issues/151)), but that would only be a temporary solution, and we'll undoubtedly be right back full circle when the next breaking change hits. 

I know @lloeki would also be in favor of someone forking and creating a newer version of this tool, and he would likely even promote that tool on the README of this one if it showed dedication to being maintained and supported.

**Comment by jazzpi** [comment]
I'm very sorry I've been this inactive, had a busy last few weeks. I should have a bit of time on my hands next week though and I'll try to weed through at least a few issues. For now though, thanks a lot for this PR!

**Comment by AsaAyers** [comment]
You're welcome, and I think that's just a normal cycle of open source. I have maintained CoffeeLint for a few years now. Since I don't think CoffeeScript has a future, I have stopped using it and I rarely look at CoffeeLint.

I opened an issue in `vim-mode` proposing that the two projects just merge. From my perspective it seems like an ideal solution. Many people are confused that ex doesn't come with `vim-mode`.

**Comment by mdarby** [comment]
Thank you for merging! You wouldn't believe how much I rely on this! :)

**Pull request merged**
