### PR TITLE
release v0.9.0

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
Update changelog, bump version

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
@jazzpi you want to take a look at the `v0.9.0` just to get one last pair of eyeballs on it before we release?

@lloeki are you the only one who can publish `ex-mode` into the `apm` registry, or can Jasper and I do this as well?

**Comment by lloeki** [comment]
IIRC apm integrates with github and any project collaborator can publish a version for that project.

**Comment by jazzpi** [comment]
Whoops, I forgot about this one, sorry. Add #148 to the changelog and then publish? Looks fine :+1:

**Comment by LongLiveCHIEF** [comment]
Yep. Will do.

**Pull request merged**
