### PR TITLE
[needs tests] Support vim-mode-plus substitute command

### PR DESCRIPTION
**Pull request by mkiken**
Fixes # 128.

Changes Proposed in this Pull Request:

- Fix substitute command error in vim-mode-plus
  Error caused by `searchHistory` functions not existing, so I add if statements.

I have written tests for: Nothing
  Sorry, I'm not sure how to test and how to write this test case...

### CODE REVIEW

**Comment by mkiken** [comment]
test failed :(
But in my environment(vim-mode 0.66.0, ex-mode 0.14.0), `substitute/,/\n/g` command to `abc,def,ghi`, result is
```
abc

def,ghi
```
Why?
Is my environment is broken?

**Comment by jazzpi** [comment]
The tests are failing due to atom/text-buffer#224. If you are using an official version of Atom (i.e. downloaded from https://atom.io) and can confirm that bug, it might help speed up work on that.

However, the tests are currently not running on vim-mode-plus anyways, but one vim-mode. I'll hopefully get around to testing this soon™ though.

**Comment by mkiken** [comment]
@jazzpi 
I usually use Atom installed by HomeBrew.Version is 1.15.0.
I try to command above using official version Atom(version 1.15.0), and confirm above bug.

I hope this helps.

**Comment by jazzpi** [comment]
I'll rewrite the specs myself, it's not actually too much effort.

**Pull request merged**
